package com.webcaisse.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-26T23:00:20.970+02:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "CaisseManagerServiceImplService", 
                  wsdlLocation = "http://localhost:7777/caisse_ws/gestionCaisse?wsdl",
                  targetNamespace = "http://ws.webcaisse.com/") 
public class CaisseManagerServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.webcaisse.com/", "CaisseManagerServiceImplService");
    public final static QName CaisseManagerServiceImplPort = new QName("http://ws.webcaisse.com/", "CaisseManagerServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:7777/caisse_ws/gestionCaisse?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CaisseManagerServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:7777/caisse_ws/gestionCaisse?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CaisseManagerServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CaisseManagerServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CaisseManagerServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CaisseManagerServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CaisseManagerServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CaisseManagerServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns CaisseManagerService
     */
    @WebEndpoint(name = "CaisseManagerServiceImplPort")
    public CaisseManagerService getCaisseManagerServiceImplPort() {
        return super.getPort(CaisseManagerServiceImplPort, CaisseManagerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CaisseManagerService
     */
    @WebEndpoint(name = "CaisseManagerServiceImplPort")
    public CaisseManagerService getCaisseManagerServiceImplPort(WebServiceFeature... features) {
        return super.getPort(CaisseManagerServiceImplPort, CaisseManagerService.class, features);
    }

}
