package com.webcaisse.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-26T23:00:20.917+02:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://ws.webcaisse.com/", name = "CaisseManagerService")
@XmlSeeAlso({ObjectFactory.class})
public interface CaisseManagerService {

    @WebMethod
    @RequestWrapper(localName = "getFamillesActivees", targetNamespace = "http://ws.webcaisse.com/", className = "com.webcaisse.ws.GetFamillesActivees")
    @ResponseWrapper(localName = "getFamillesActiveesResponse", targetNamespace = "http://ws.webcaisse.com/", className = "com.webcaisse.ws.GetFamillesActiveesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.webcaisse.ws.Famille> getFamillesActivees();

    @WebMethod
    @RequestWrapper(localName = "getProduitParFamilleReference", targetNamespace = "http://ws.webcaisse.com/", className = "com.webcaisse.ws.GetProduitParFamilleReference")
    @ResponseWrapper(localName = "getProduitParFamilleReferenceResponse", targetNamespace = "http://ws.webcaisse.com/", className = "com.webcaisse.ws.GetProduitParFamilleReferenceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.webcaisse.ws.Produit> getProduitParFamilleReference(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
